### PR TITLE
Day 1 - Challenge

### PR DESCRIPTION
**Pull request by mangzee**
A basic function app using c# ;)

### CODE REVIEW

**Comment by glaucia86** [comment]
Hi @mangzee!

Once you have the challenge result, you will compare it to the challenge you created. And after make all the necessary changes in your code, we will close this PR.
Remember that all challenges must be developed in your repository. That's why is very important to fork this repository.

And thank you for your awesome contribution @mangzee !

bitmoji

**Comment by mangzee** [comment]
Hey @glaucia86 ,
I have updated the PR with Day 2 solution.
Have a great day ahead :)

**Comment by mangzee** [comment]
Hey @glaucia86 ,
Updated with Day 3 solution :)

**Comment by jansche** [comment]
Hi @mangzee 
Please submit further solutions as **ISSUES** not as PRs.
For Challenge 1 we checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contribution!
This PR is now closed! 🎉

**Comment by jansche** [comment]
Hi @mangzee
Please submit further solutions as ISSUES not as PRs.
For Challenge 2 we checked out your repository. We're thrilled to say your solution is now listed in our Hall of Fame.
Thank you for your contribution!
This PR is now closed! 🎉

**Comment by jansche** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
Starting Dec 4, 2019 we have changed our contribution process to use **ISSUES** and not PRs. 
You can learn more about the change [here](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTING.md).  
We hope this makes the process simpler for both contributors and reviewers. 

We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions!
This PR is now closed! 🎉

**Pull request closed without merging**
