### PR TITLE
Add link to wbprice's solution for challenge 1

### PR DESCRIPTION
**Pull request by wbprice**

### CODE REVIEW

**Comment by glaucia86** [comment]
Hi @wbprice !

Once you have the challenge result, you will compare it to the challenge you created. And after make all the necessary changes in your code, we will close this PR.
Remember that all challenges must be developed in your repository. That's why is very important to fork this repository.

And thank you for your awesome contribution @wbprice  !

bitmoji

**Comment by wbprice** [comment]
Hi @glaucia86.  I'm a little confused. What changes do you need me to make? Is something wrong with https://github.com/wbprice/25-days-of-serverless-2019-solutions/blob/master/1/?

**Comment by wbprice** [comment]
I updated the link to read `https://github.com/wbprice/25-days-of-serverless/tree/wbprice-solution-1/week-1/challenge-1`, is this what you had in mind?

**Comment by glaucia86** [comment]
> Hi @glaucia86. I'm a little confused. What changes do you need me to make? Is something wrong with https://github.com/wbprice/25-days-of-serverless-2019-solutions/blob/master/1/?

nothing. Just telling you about this PR's. It's everything correct @wbprice

**Comment by jansche** [comment]
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions!
This PR is now closed! 🎉

**Pull request closed without merging**
