### PR TITLE
Update Contributors File

### PR DESCRIPTION
**Pull request by Danushka96**

### CODE REVIEW

**Comment by Danushka96** [comment]
My solution for challenge 1

**Comment by glaucia86** [comment]
Hi @ncsuWolfpack!

Thank you so much for your awesome contribution.

Please, include your name in the CONTRIBUTORS.md file here: https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md

bitmoji

**Comment by Danushka96** [comment]
I included my name in this file.

**Comment by jansche** [comment]
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions!
This PR is now closed! 🎉

**Comment by Danushka96** [comment]
Thank You!!

**Pull request closed without merging**
