### PR TITLE
Day 1 submission

### PR DESCRIPTION
**Pull request by madebygps**
My submission to day 1 challenge.

### CODE REVIEW

**Comment by glaucia86** [comment]
Hi @madebygps!

Once you have the challenge result, you will compare it to the challenge you created. And after make all the necessary changes in your code, we will close this PR.
Remember that all challenges must be developed in your repository. That's why is very important to fork this repository.

And thank you for your awesome contribution @madebygps!

bitmoji

**Comment by madebygps** [comment]
Adding solution for day #2

**Comment by madebygps** [comment]
Am I supposed to create a new pull request to merge updates for day 2?

**Comment by jansche** [comment]
We checked out your repository. We're thrilled to say your solution for challenge 1 is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions!

**Comment by jansche** [comment]
We checked out your repository. We're thrilled to say your solution to challenge 2 is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions!

Starting Dec 4, 2019 we have changed our contribution process to use **ISSUES** and not PRs. 
You can learn more about the change [here](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTING.md).  
We hope this makes the process simpler for both contributors and reviewers.

This PR is now closed! 🎉

**Pull request closed without merging**
